# 检查numpy

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.5


# 认识ndarray和shape

## 1. Numpy 数组与 shape
shape描述数组在每一个维度上的长度

- 标量：shape = ()
- 一维向量：shape = (n,)
- 二维矩阵：shaoe = (m,n)

In [26]:
scalar = np.array(5)

vector = np.array([1,2,3])

matrix_2 = np.array([[1,2,3]])
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print("scalar:")
print(scalar)
print("shape:",scalar.shape)

print()

print("vector:")
print(vector)
print("shape:",vector.shape)

print()

print("matrix_2:")
print(matrix_2)
print("shape:",matrix_2.shape)
print()
print("matrix:")
print(matrix)
print("shape:",matrix.shape)

scalar:
5
shape: ()

vector:
[1 2 3]
shape: (3,)

matrix_2:
[[1 2 3]]
shape: (1, 3)

matrix:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)


## 2. Numpy的逐元素运算
`+ - * /`通常进行逐元素运算。
它们不是矩阵乘法

In [ ]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print("a + b = ",a+b)
print("a * b = ",a*b)

a + b =  [11 22 33]
a * b =  [10 40 90]


## 3. Broadcasting

广播：当两个数组的shape不完全相同时，
NumPy 在满足一定规则的情况下，可以自动扩展小数组进行逐元素运算。

判断广播时，从shape的最后一维开始向前比较。

两个维度满足以下任意一个条件即可兼容：
1. **两个维度相等**
2. **其中一个维度为1**

（1）首先是最简单的广播：数组+标量

In [9]:
a = np.array([1,2,3])

print("a + 10 = ",a + 10)

a + 10 =  [11 12 13]


可以想象为：
原来：
[1, 2, 3] + 10

概念上 NumPy 把 10 广播成：
[1, 2, 3] + [10,10,10] = [11,12,13]

（2）二维数组 + 一维数组

In [10]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([10,20,30])

print("shape of a:", a.shape)
print("shape of b:", b.shape)

print(a + b)

shape of a: (2, 3)
shape of b: (3,)
[[11 22 33]
 [14 25 36]]


从shape看：a：(2,3)、b：(3,)
从右往左比较：最后一维均为3，相同

然后可以把b概念上理解成[[10,20,30],[10,20,30]]

于是：
    [[1,2,3],      [[10,20,30],
 [4,5,6]]   +   [10,20,30]]=
[[11,22,33],
 [14,25,36]]

（3）广播中非常重要的（2，1）

In [11]:
a = np.array([
    [1],
    [2]
])
b = np.array([10,20,30])

print("shape of a:",a.shape)
print("shape of b:",b.shape)
print(a + b)

shape of a: (2, 1)
shape of b: (3,)
[[11 21 31]
 [12 22 32]]


shape对齐：  
a: (2, 1)  
b:    (3,)  
补齐理解成：  
a: (2, 1)  
b: (1, 3)  
从右开始：  
1 和 3 其中一个为1  
2 和 1 其中一个为1  
所以最后shape：(2,3)

（4）故意制造广播错误

In [12]:
a = np.ones((2,3))
b = np.array([10,20])

print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

显然可知，从右开始，维度分别为3、2，既不相等又不为1，因此无法进行广播运算

## 4. 矩阵乘法
如果：  
A.shape = (m,n)  
B.shape = (n,p)  
那么：A @ B 的结果shape为：(m,p)
矩阵乘法要求：A 的列数 = B 的行数

In [13]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print("A shape:", A.shape)
print("B shape:", B.shape)

C = A @ B
print("C:")
print(C)
print("C shape:", C.shape)

A shape: (2, 3)
B shape: (3, 2)
C:
[[22 28]
 [49 64]]
C shape: (2, 2)


## 5. 向量点积
两个向量：  
a = [a1, a2, ..., an]  

b = [b1, b2, ..., bn]  

点积结果：  
a · b = a1*b1 + a2*b2 + ... + an*bn

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a · b = ",np.dot(a,b))

a · b =  32


## 6. 均值与方差
均值表示数据的中心位置  
方差表述数据围绕均值的离散程度

In [15]:
x = np.array([1,2,3,4])

mean = np.mean(x)
var = np.var(x)

print("mean:",mean)
print("var:",var)

mean: 2.5
var: 1.25


In [16]:
x = np.array([1,2,3,4])
manual_mean = np.sum(x) / len(x)
manual_var = np.mean((x-manual_mean) ** 2)
print(manual_mean)
print(manual_var)

2.5
1.25


## 7. Softmax

Softmax将一组任意实数转换成概率分布。  

性质：  
1. 每一个输出都大于0  
2. 所有输出之和为1  

Softmax: softmax(x_i) = e^x_i / sigma_j(e^x_j)  
例如：  
x = [1,2,3]  
经过softmax之后会变成类似:  
[0.09,0.24,0.67]  

In [17]:
def softmax_naive(x):
    exp_x = np.exp(x)
    return exp_x/np.sum(exp_x)

x = np.array([1.0, 2.0, 3.0])

prob = softmax_naive(x)

print(prob)
print("sum=", np.sum(prob))

[0.09003057 0.24472847 0.66524096]
sum= 1.0


为什么Softmax输出概率和一定为1
通过softmax的定义式即可看出，其分母项为所有分子项之和，因此输出概率和一定为1

In [18]:
x = np.array([1000.0, 1000.0])
print(np.exp(x))

[inf inf]


C:\Users\fallwind\AppData\Local\Temp\ipykernel_40140\1481996893.py:2: RuntimeWarning: overflow encountered in exp
  print(np.exp(x))


输出inf是因为e^1000很大，超过了浮点数可表示的范围，因此上溢为inf。  
同时会导致朴素Softmax实现的输出为nan，出现问题，因为用inf进行计算时未定义的数值操作

In [20]:
x = np.array([1000.0, 1000.0])
x_shifted = x - np.max(x)
print(x_shifted)
print(np.exp(x_shifted))

[0. 0.]
[1. 1.]


In [21]:
exp_x = np.exp(x_shifted)
prob = exp_x / np.sum(exp_x)
print(prob)

[0.5 0.5]


**为什么减max不改变softmax**  
原来e^x_i / sigma_j(e^x_j)，当所有元素减去同一个c时：  
e^(x_i-c) / sigma_j(e^(x_j-c)) = e^x_i * e^(-c) / sigma_j(e^x_j) * e^(-c) = e^x_i / sigma_j(e^x_j)  
因此：**减去同一个数不会改变softmax的结果**

**写出稳定Softmax**

In [22]:
def softmax(x):
    x_shifted = x - np.max(x)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x)

x = np.array([1000.0, 1000.0])
prob = softmax(x)
print(prob)
print("sum=", np.sum(prob))
print("sum close to 1", np.isclose(np.sum(prob), 1.0))

[0.5 0.5]
sum= 1.0
sum close to 1 True


对[1000, 1001, 1002]进行测试

In [23]:
x = np.array([1000.0, 1001.0, 1002.0])

print("shift before:")
print(x)

print("shift after:")
print(x - np.max(x))

print("softmax:")
print(softmax(x))

print("sum:")
print(np.sum(softmax(x)))

shift before:
[1000. 1001. 1002.]
shift after:
[-2. -1.  0.]
softmax:
[0.09003057 0.24472847 0.66524096]
sum:
0.9999999999999999


**进阶：二维Softmax**  

神经网络真正实用的通常不是：(3,)  
而可能是：(batch_size, num_classes)  

In [24]:
x = np.array([
    [1.0, 2.0, 3.0],
    [1000.0, 1001.0, 1002.0]
])

def softmax_2d(x):
    x_shifted = x - np.max(x, axis=1, keepdims=True)
    exp_x = np.exp(x_shifted)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

prob = softmax_2d(x)
print(prob)
print(prob.sum(axis=1))

[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]
[1. 1.]


对以上代码进行解析：  
**首先是axis=1**：表示沿着每一行计算，即针对不同列（axis=0是不同行，1是不同列，以此类推）   
**keepdims=True**：保留维度，方便broadcasting，如果不加，那么经过np.max后会降维，形状从(N,C)变为(N,)。然后再将x(N,C)与其相减，从右向左对齐维度，(N,)视作(1,N)，N!=C，因此会导致广播错误。当加上keepdims=True后，取max后维度变为(N,1)

## 8. W1D3总结实验

In [25]:
#1. shape
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [1,2],
    [3,4],
    [5,6]
])
print("=== Matrix shape ===")
print("A:",A.shape)
print("B:",B.shape)
print("A@B:",(A@B).shape)

#2. broadcasting
x = np.array([
    [1,2,3],
    [4,5,6]
])
bias = np.array([10,20,30])

print("\n=== Broadcasting ===")
print(x + bias)  #应为([11,22,33],[14,25,36])

# 3. dot product
a = np.array([1,2,3])
b = np.array([4,5,6])

print("\n=== Dot product ===")
print(np.dot(a,b))  #32

# 4. statistics
values = np.array([1, 2, 3, 4])

print("\n=== Statistics ===")
print("mean:",np.mean(values))
print("variance:",np.mean((values-np.mean(values))**2))

# 5. stable softmax
logits = np.array([1000.0, 1001.0, 1002.0])

probabilities = softmax(logits)

print("\n=== Stable Softmax ===")
print(probabilities)
print("sum:", np.sum(probabilities))

=== Matrix shape ===
A: (2, 3)
B: (3, 2)
A@B: (2, 2)

=== Broadcasting ===
[[11 22 33]
 [14 25 36]]

=== Dot product ===
32

=== Statistics ===
mean: 2.5
variance: 1.25

=== Stable Softmax ===
[0.09003057 0.24472847 0.66524096]
sum: 0.9999999999999999


## 9.易犯错误总结
（1）把(3,)当成(3,1)  
并不是，(3,)是一维向量，而(3,1)是二维矩阵，三行一列  

（2）把*当作矩阵乘法  
错误，*是逐元素乘法，矩阵乘法是@  

（3）矩阵乘法只看元素数量  
不是，必须看中间两个维度是否相等  

（4）广播从左往右比较  
错误，广播应当从右往左比较shape  

（5）Softmax直接np.max(x)  
对于小数据可能没事，但是数据的值较大，会出现上溢的情况导致计算未定式，应当先减去最大值